version: '3.8'

services:
  app:
    build: .
    container_name: blog_api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:6
    container_name: blog_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
