version: "3.8"

services:
  app:
    image: carolinesant/blog:desenvolvimento
    container_name: blog_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
