name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Definir tag da imagem baseada na branch
      - name: Definir tag da imagem
        id: tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      # Build e push da imagem para Docker Hub
      - name: Build e push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: carolinesant/blog:${{ steps.tag.outputs.tag }}

      # Atualizar containers com docker-compose
      - name: Atualizar containers
        run: |
          docker compose pull app
          docker compose up -d

      # Mensagem de conclusão
      - name: Finalização
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "Imagem enviada com sucesso para o Docker Hub (tag: $TAG)"
