name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Login no Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2️⃣ Definir tag da imagem
      - name: Definir tag da imagem
        id: tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      # 3️⃣ Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            # Vai para a pasta do projeto (não para o arquivo docker-compose.yml)
            cd ~/blogversao2

            # Exporta variáveis de ambiente
            export DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}"
            export PORT=3000

            # Atualiza e recria containers
            docker-compose pull app
            docker-compose up -d --force-recreate

            # Limpa imagens antigas
            docker image prune -af
