name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir tag da imagem
        id: tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /caminho/do/docker-compose

            # Exporta variáveis do MongoDB Atlas e porta
            export DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}"
            export PORT=3000

            # Puxa a imagem e recria o container
            docker-compose pull app
            docker-compose up -d --force-recreate

            docker image prune -af
