name: CD - Build e Push Docker Image

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir tag da imagem
        id: tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Set environment
        run: |
          export DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
          export PORT=3000

      - name: Build da imagem Docker
        run: docker build -t carolinesant/blog:${{ steps.tag.outputs.tag }} .

      - name: Push da imagem para o Docker Hub
        run: docker push carolinesant/blog:${{ steps.tag.outputs.tag }}
