name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main
      - desenvolvimento # Workflow acionado para ambas as branches

jobs:
  build-and-deploy:
    name: Build e Push para Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: carolinesant/blog:desenvolvimento

      - name: Atualizar containers com docker-compose
        run: |
          docker-compose pull app
          docker-compose up -d

      # Definir tag da imagem baseada na branch
      - name: Definir tag da imagem
        id: tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            fi

      # Build da imagem Docker
      - name: Build da imagem Docker
        run: |
          docker build -t carolinesant/blog:${{ steps.tag.outputs.tag }} .

      # Push da imagem para o Docker Hub
      - name: Push para o Docker Hub
        run: |
          docker push carolinesant/blog:${{ steps.tag.outputs.tag }}

      # Mensagem de conclusão
      - name: Finalização
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "Imagem enviada com sucesso para o Docker Hub (tag: $TAG)"
